import type { Model, Quant } from "../types";
import sizesJson from "../../data/model-sizes.json";

/**
 * Model catalog.
 *
 * GGUF sizes are read from `sim/data/model-sizes.json`, which is generated by
 * `tools/refresh_data.py` directly from the Hugging Face API (exact blob
 * sizes; split files summed). Nothing here is hand-entered or estimated: a
 * `null` size means the repo exposes no artifact for that quant and the engine
 * refuses to simulate it.
 */

interface Blob {
  bytes: number;
  files: string[];
}

const SIZES = sizesJson.models as Record<
  string,
  { repo: string; q4_k_m: Blob | null; q8_0: Blob | null; bf16: Blob | null }
>;

/** HF blob bytes -> decimal GB rounded to two decimals (matching published repo tables). */
function gb(blob: Blob | null | undefined): number | null {
  return blob ? Math.round(blob.bytes / 1e7) / 100 : null;
}

const VERIFIED = `sizes verified from the Hugging Face API (tools/refresh_data.py, ${sizesJson.retrieved})`;

export const MODELS: Model[] = [
  {
    id: "qwen3.5_4b",
    name: "Qwen3.5-4B",
    totalParamsB: 4.0,
    activeParamsB: 4.0,
    layers: 32,
    attentionHeads: 32,
    hiddenSize: 2560,
    kvHeads: 8,
    headDim: 80,
    quantSizesGb: {
      q4_k_m: gb(SIZES["qwen3.5_4b"]?.q4_k_m),
      q8_0: gb(SIZES["qwen3.5_4b"]?.q8_0),
      bf16: gb(SIZES["qwen3.5_4b"]?.bf16),
    },
    source: "https://huggingface.co/bartowski/Qwen_Qwen3.5-4B-GGUF",
    status: `architecture_partly_observed; ${VERIFIED}`,
  },
  {
    id: "llama3.1_8b",
    name: "Llama-3.1-8B-Instruct",
    totalParamsB: 8.03,
    activeParamsB: 8.03,
    layers: 32,
    attentionHeads: 32,
    hiddenSize: 4096,
    kvHeads: 8,
    headDim: 128,
    quantSizesGb: {
      q4_k_m: gb(SIZES["llama3.1_8b"]?.q4_k_m),
      q8_0: gb(SIZES["llama3.1_8b"]?.q8_0),
      bf16: gb(SIZES["llama3.1_8b"]?.bf16),
    },
    source: "https://huggingface.co/bartowski/Meta-Llama-3.1-8B-Instruct-GGUF",
    status: `architecture_from_meta_config; ${VERIFIED}`,
  },
  {
    id: "gemma3_27b",
    name: "Gemma-3-27B-it",
    totalParamsB: 27.0,
    activeParamsB: 27.0,
    layers: 62,
    attentionHeads: 32,
    hiddenSize: 5376,
    kvHeads: 16,
    headDim: 128,
    quantSizesGb: {
      q4_k_m: gb(SIZES["gemma3_27b"]?.q4_k_m),
      q8_0: gb(SIZES["gemma3_27b"]?.q8_0),
      bf16: gb(SIZES["gemma3_27b"]?.bf16),
    },
    source: "https://huggingface.co/bartowski/google_gemma-3-27b-it-GGUF",
    status: `architecture_from_config; ${VERIFIED}`,
  },
  {
    id: "qwen3_32b",
    name: "Qwen3-32B",
    totalParamsB: 32.0,
    activeParamsB: 32.0,
    layers: 64,
    attentionHeads: 64,
    hiddenSize: 5120,
    kvHeads: 8,
    headDim: 128,
    quantSizesGb: {
      q4_k_m: gb(SIZES["qwen3_32b"]?.q4_k_m),
      q8_0: gb(SIZES["qwen3_32b"]?.q8_0),
      bf16: gb(SIZES["qwen3_32b"]?.bf16),
    },
    source: "https://huggingface.co/bartowski/Qwen_Qwen3-32B-GGUF",
    status: `architecture_from_model_config; ${VERIFIED}`,
  },
  {
    id: "qwen3.5_35b_a3b",
    name: "Qwen3.5-35B-A3B",
    totalParamsB: 35.0,
    activeParamsB: 3.0,
    layers: 40,
    attentionHeads: 32,
    hiddenSize: 4096,
    kvHeads: 8,
    headDim: 128,
    quantSizesGb: {
      q4_k_m: gb(SIZES["qwen3.5_35b_a3b"]?.q4_k_m),
      q8_0: gb(SIZES["qwen3.5_35b_a3b"]?.q8_0),
      bf16: gb(SIZES["qwen3.5_35b_a3b"]?.bf16),
    },
    source: "https://huggingface.co/bartowski/Qwen_Qwen3.5-35B-A3B-GGUF",
    status: `moe_architecture; ${VERIFIED}`,
  },
  {
    id: "llama3.3_70b",
    name: "Llama-3.3-70B-Instruct",
    totalParamsB: 70.6,
    activeParamsB: 70.6,
    layers: 80,
    attentionHeads: 64,
    hiddenSize: 8192,
    kvHeads: 8,
    headDim: 128,
    quantSizesGb: {
      q4_k_m: gb(SIZES["llama3.3_70b"]?.q4_k_m),
      q8_0: gb(SIZES["llama3.3_70b"]?.q8_0),
      bf16: gb(SIZES["llama3.3_70b"]?.bf16),
    },
    source: "https://huggingface.co/bartowski/Llama-3.3-70B-Instruct-GGUF",
    status: `architecture_from_meta_config; ${VERIFIED}`,
  },
  {
    id: "gpt_oss_120b",
    name: "GPT-OSS-120B",
    totalParamsB: 117.0,
    activeParamsB: 5.1,
    layers: 36,
    attentionHeads: 64,
    hiddenSize: 2880,
    kvHeads: 8,
    headDim: 64,
    quantSizesGb: {
      q4_k_m: gb(SIZES["gpt_oss_120b"]?.q4_k_m),
      q8_0: gb(SIZES["gpt_oss_120b"]?.q8_0),
      bf16: gb(SIZES["gpt_oss_120b"]?.bf16),
    },
    source: "https://huggingface.co/bartowski/openai_gpt-oss-120b-GGUF",
    status: `moe_architecture_mxfp4_format; ${VERIFIED}`,
  },
  {
    id: "minimax_m2.5",
    name: "MiniMax-M2.5",
    totalParamsB: 230.0,
    activeParamsB: 10.0,
    layers: 62,
    attentionHeads: 64,
    hiddenSize: 4096,
    kvHeads: 8,
    headDim: 128,
    quantSizesGb: {
      q4_k_m: gb(SIZES["minimax_m2.5"]?.q4_k_m),
      q8_0: gb(SIZES["minimax_m2.5"]?.q8_0),
      bf16: gb(SIZES["minimax_m2.5"]?.bf16),
    },
    source: "https://huggingface.co/ox-ox/MiniMax-M2.5-GGUF",
    status: `moe_architecture_partial; ${VERIFIED}`,
  },
];

/** True when the catalog carries a verified size for this model+quant. */
export function hasVerifiedSize(model: Model, quant: Quant): boolean {
  return model.quantSizesGb[quant] != null;
}
