import modelContextJson from "../../data/model-context.json";

/**
 * Verified context windows, one row per model.
 *
 * Source: the models' own GGUF metadata via the Hugging Face API
 * (`?expand[]=gguf` -> `gguf.context_length`), the same field llama.cpp reads
 * from the file header. Generated by `tools/refresh_context.py`; no figure here
 * is estimated, and a model with no verified row returns null rather than a guess.
 */
export const MODEL_CONTEXT = modelContextJson as unknown as {
  retrieved: string;
  method: string;
  models: Record<string, { repo: string; contextLength: number | null; architecture?: string }>;
};

/** The model's own context limit, or null when there is no verified figure. */
export function maxContextTokens(modelId: string): number | null {
  const row = MODEL_CONTEXT.models[modelId];
  return row && typeof row.contextLength === "number" ? row.contextLength : null;
}
